spring:
  datasource:
    url: jdbc:mysql://47.101.171.252:3306/SpringLearning
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 15
    timeout: 0
    pool:
      maxTotal: 8
      maxWaitMillis: 1000
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
logging:
  level:
    com:
      ly:
        springdemo:
          Mapper: DEBUG

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.ly.springdemo.Entity
  configuration:
    cache-enabled: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql