spring:
  datasource:
    url: jdbc:mysql://47.101.171.252:3306/SpringLearning
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com:
      ly:
        springdemo:
          Mapper: DEBUG

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.ly.springdemo.Entity
  configuration:
    cache-enabled: true
